name: Code Checks
on: push
jobs:
  test-python-versions:
    name: Check python ${{ matrix.python-version }} on ubuntu
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        allow_failure: [false]
        include:
          - python-version: "3.12.0-beta.4"
            allow_failure: true
    continue-on-error: ${{ matrix.allow_failure }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Setup python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: python -m pip install -e .[test]
      - name: Test package
        run: python -m pytest

